services:

  database:
    build:
      context: ./postgresql
    # volumes:
      # - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: ./env/.env
    networks:
      - internal
    expose:
      - ${PORT_POSTGRES}
    ports:
      - ${PORT_POSTGRES}:${PORT_POSTGRES}

  backend:
    build:
      context: ./back-nestjs
    volumes:
      - ./back-nestjs:/app
      - nestjs_modules:/app/node_modules
    restart: unless-stopped
    env_file: ./env/.env
    depends_on:
      - database
    expose:
      - ${PORT_BACKEND}
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    networks:
      - internal

  frontend:
    build:
      context: ./front-vite
    volumes:
      - ./front-vite:/app
      - react_modules:/app/node_modules
    restart: unless-stopped
    env_file: ./env/.env
    depends_on:
      - backend
    expose:
      - ${PORT_FRONTEND}
    ports:
      - ${PORT_FRONTEND}:${PORT_FRONTEND}
    networks:
      - internal

volumes:
  # pgdata:
  react_modules:
  nestjs_modules:

networks:
  internal:
    driver: bridge
