name: Setup Secrets

on:
  workflow_dispatch:

jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preserve existing env-file file
        run: |
          if [ -f env-file ]; then
            echo "env-file file already exists, appending secrets..."
          else
            echo "env-file file not found, creating a new one."
            touch env-file
          fi

      - name: Append secrets to env-file
        run: |
          echo "# SECRET TOKENS" >> env-file 
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> env-file
          echo "SECRET_PWD=${{ secrets.SECRET_PWD }}" >> env-file
          echo "SECRET_UID=${{ secrets.SECRET_UID }}" >> env-file

      - name: Verify env-file file (without exposing secrets)
        run: cat env-file | sed 's/=.*/=********/'

      - name: Check if env-file exists
        run: |
          ls -lah
          pwd

      - name: Upload env-file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: env-file
